# .goreleaser.yml
project_name: xq

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X main.buildDate={{.Date}}
      - -X main.gitVersion={{.Tag}}
      - -X main.gitHash={{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
    id: "delorean"
    dir: .
    main: .
    hooks:
      post: 'upx --brute {{ .Path }}'

archives:
  - format: tar.gz
    replacements:
      amd64: x86_64

changelog:
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^refactor'
      - '^style'
      - '^test'